baseurl: "/resume" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://ahyat098.github.io/resume/" # the base hostname & protocol for your site

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
